language: ruby
rvm:
  - 2.1
install: gem install github-pages && gem install s3_website
branches:
  except:
    - master
before_deploy: jekyll build
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: "digidem-staging"
  skip_cleanup: true
  upload-dir: ${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}
  local_dir: _site
  detect_encoding: true
