# Site settings
title: Digital Democracy Lab
email: info@digital-democracy.org
description: Digital Democracy (Dd) is a US-based nonprofit that empowers indigenous peoples with evidence-based storytelling tools to defend the world’s forests and critical ecosystems. We draw upon a wide network of partners around the world to build tools and provide technical support where it is needed most. This site introduces the tools, big and small, that we’ve created with our mapping and monitoring partners.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: digidem
github_username:  digidem

# Build settings
markdown: kramdown
permalink: pretty # for blog posts
# pages are always /folder/title
